Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.uaian.aws.lambda.processor.excel.parse.ExcelParseS3TriggerProcessor
      CodeUri: /Users/kainan/IdeaProjects/codex-java/codex-aws
      Runtime: java11
      Architectures:
        - x86_64